/**
 * Put the WebAssembly parser inside the package, as text.
 *
 * web-ifc ships `web-ifc.wasm` as a separate file and fetches it beside the
 * script that loaded it. That works when a host copies the file into its own
 * output, which means the host has to be told to do so: a postinstall step, a
 * bundler rule, or a served path. Every one of those is configuration a
 * consumer has to get right, and DTaaS has to work with no external network at
 * all.
 *
 * So the binary is written into a module as base64 and turned back into a blob
 * at runtime. It costs about a third more bytes than the file, in a chunk that
 * a host fetches only when someone actually converts a model, and it buys a
 * consumer that installs the package and nothing else.
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join } from 'node:path';
import { createRequire } from 'node:module';

// Ask Node where web-ifc actually is instead of assuming it sits in this
// package's own node_modules. In a workspace the install is hoisted to the
// root, so a hand-built relative path finds nothing and the build stops with
// an ENOENT that says nothing about the cause.
const require = createRequire(import.meta.url);
const wasmPath = join(dirname(require.resolve('web-ifc')), 'web-ifc.wasm');
const outputPath = 'src/converter/generated/wasm.ts';

// Repeated test runs call this script through `yarn wasm`; skip the base64
// re-encode when the generated file is already newer than its source.
const isUpToDate = () =>
  existsSync(outputPath) &&
  statSync(outputPath).mtimeMs > statSync(wasmPath).mtimeMs;

if (!isUpToDate()) {
  const wasm = readFileSync(wasmPath);
  const base64 = wasm.toString('base64');

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(
    outputPath,
    `/* eslint-disable */
// Generated by scripts/inline-wasm.mjs. Do not edit.
//
// web-ifc.wasm, ${(wasm.length / 1024).toFixed(0)} KB, as base64.

// The type annotation is what keeps the declaration file one line long.
// Without it TypeScript infers the literal type and writes the whole 1.7 MB
// of base64 into the .d.ts as a type, which doubles what a consumer
// downloads and says nothing a consumer can use.
export const WEB_IFC_WASM_BASE64: string =
  '${base64}';
`,
  );

  // Build tooling output, not application logging.
  // eslint-disable-next-line no-console
  console.log(
    `  web-ifc.wasm inlined: ${(wasm.length / 1024).toFixed(0)} KB binary, ${(base64.length / 1024).toFixed(0)} KB base64`,
  );
} else {
  // eslint-disable-next-line no-console
  console.log('  web-ifc.wasm already inlined, skipping');
}
